### ISSUE TITLE
Work with set, get, copy, etc. operators

### ISSUE THREAD

**Issue by EmaX093** [cerebral/cerebral-provider-modules#4]
Hi! I want to know if is possible to make this work with set, get, copy, etc. operators

**Comment by EmaX093** [comment]
What do you think about using a flag in the url scheme, like **global/state** ?

`set('global/state:app.loading', true)` // For global scope
`set('local/state:loading', true)` // For local (module) scope explicit
`set('state:loading', true)` // Local (module) scope by default (implicit)

**Comment by Guria** [comment]
Now we recommend use template strings and constants:

``` js
import { MODULEPATH } from '../constants'

export default [
  set(`state:${MODULEPATH}.isLoading`, true)
]
```

**Comment by EmaX093** [comment]
Okay then! Thank you Guria!
